document.addEventListener('DOMContentLoaded', () => {
  const $ = selector => document.querySelector(selector);
  const views = ['home', 'folder', 'notebook', 'calendar', 'dashboard'];
  let activeView = 'home'; let activeFolder = null;
  let editorCanvas; let editorPage; let selectedCalendarDate = null;

  function toast(message) { const item = document.createElement('div'); item.className = 'toast'; item.textContent = message; $('#toast-container').appendChild(item); setTimeout(() => item.remove(), 2600); }
  function showView(view) { activeView = view; views.forEach(name => $('#' + name + '-view').classList.toggle('active', name === view)); document.querySelectorAll('.nav-item').forEach(item => item.classList.toggle('active', item.dataset.view === view)); if (view === 'dashboard') renderDashboard(); if (view === 'calendar') renderCalendar(); if (view === 'folder') renderFolder(); if (view === 'notebook') openNotebook(InkNotebook.currentNotebook || InkStorage.data.notebooks[0]?.id); }
  function toggleSidebar() { $('#sidebar').classList.toggle('open'); }
  function toggleTheme() { const root = document.documentElement; root.dataset.theme = root.dataset.theme === 'dark' ? 'light' : 'dark'; localStorage.setItem('inkpad-theme', root.dataset.theme); }
  function openModal(title, callback) { $('#modal-title').textContent = title; $('#modal-input').value = ''; $('#modal-backdrop').classList.add('open'); const finish = () => { const value = $('#modal-input').value.trim(); $('#modal-backdrop').classList.remove('open'); if (value) callback(value); }; $('#modal-ok').onclick = finish; $('#modal-cancel').onclick = () => $('#modal-backdrop').classList.remove('open'); $('#modal-input').focus(); }
  function createNotebook() { openModal('Create notebook', name => { const notebook = InkNotebook.create(name); refreshSidebar(); showView('notebook'); openNotebook(notebook.id); toast('Notebook created'); }); }
  function createFolder() { openModal('Create folder', name => { InkNotebook.createFolder(name); refreshSidebar(); renderDashboard(); toast('Folder created'); }); }
  function refreshSidebar() { InkNotebook.renderSidebar(openNotebook, openNotebook, openFolder, deleteNotebook, deleteFolder); }
  function deleteNotebook(id) { const notebook = InkStorage.data.notebooks.find(item => item.id === id); if (!notebook || !confirm('Delete notebook "' + notebook.name + '" and all its pages?')) return; InkNotebook.deleteNotebook(id); refreshSidebar(); renderDashboard(); if (InkStorage.data.notebooks.length) openNotebook(InkStorage.data.notebooks[0].id); else showView('home'); toast('Notebook deleted'); }
  function deleteFolder(id) { const folder = InkStorage.data.folders.find(item => item.id === id); if (!folder || !confirm('Delete folder "' + folder.name + '"? Its notebooks will be kept.')) return; InkNotebook.deleteFolder(id); refreshSidebar(); if (activeFolder?.id === id) { activeFolder = null; showView('home'); } else renderFolder(); toast('Folder deleted'); }
  function openFolder(id) { activeFolder = InkStorage.data.folders.find(folder => folder.id === id) || null; if (!activeFolder) return; showView('folder'); }
  function renderFolder() { if (!activeFolder) return; $('#folder-view-title').textContent = activeFolder.name; $('#folder-heading-name').textContent = activeFolder.name; const notebooks = InkStorage.data.notebooks.filter(notebook => notebook.folderId === activeFolder.id); $('#folder-heading-subtitle').textContent = notebooks.length + (notebooks.length === 1 ? ' notebook' : ' notebooks'); const grid = $('#folder-notebooks'); grid.innerHTML = ''; if (!notebooks.length) { grid.innerHTML = '<div class="folder-empty">This folder is empty. Drag a notebook onto it from the sidebar.</div>'; return; } notebooks.forEach(notebook => { const card = document.createElement('button'); card.className = 'folder-notebook-card'; card.innerHTML = '<span class="folder-card-icon">📓</span><span>' + notebook.name + '</span><small>' + notebook.pages.length + (notebook.pages.length === 1 ? ' page' : ' pages') + '</small>'; card.onclick = () => openNotebook(notebook.id); card.ondblclick = () => openNotebook(notebook.id); grid.appendChild(card); }); }
  function openNotebook(id) { if (!id) return; if (activeView !== 'notebook') showView('notebook'); InkNotebook.open(id, null, { render(notebook, page) { refreshSidebar(); $('#notebook-breadcrumb-name').textContent = notebook.name; $('#notebook-breadcrumb-page').textContent = page.name; renderPages(notebook, page); const text = $('#text-layer'); text.textContent = page.text || ''; setupEditor(notebook, page); } }); }
  function renderPages(notebook, activePage) { const tabs = $('#page-tabs'); tabs.innerHTML = ''; notebook.pages.forEach(page => { const tab = document.createElement('button'); tab.className = 'page-tab' + (page.id === activePage.id ? ' active' : ''); tab.textContent = page.name; tab.onclick = () => InkNotebook.open(notebook.id, page.id, { render: (book, selected) => { $('#notebook-breadcrumb-page').textContent = selected.name; renderPages(book, selected); $('#text-layer').textContent = selected.text || ''; setupEditor(book, selected); } }); tabs.appendChild(tab); }); const add = document.createElement('button'); add.className = 'page-tab'; add.textContent = '+ Page'; add.onclick = () => { const page = InkNotebook.addPage(); if (page) openNotebook(notebook.id); }; tabs.appendChild(add); }
  function setupEditor(notebook, page) { editorPage = page; if (!editorCanvas) { editorCanvas = InkCanvas.setup($('#drawing-canvas'), () => { if (editorPage) editorPage.drawing = editorCanvas.toDataUrl(); InkStorage.save(); updateHistoryButtons(editorCanvas); }); bindCanvasControls(editorCanvas); $('#text-layer').oninput = () => { if (editorPage) { editorPage.text = $('#text-layer').innerText; InkStorage.save(); } }; } editorCanvas.resize(); setEditorMode('draw'); editorCanvas.reset(); if (page.drawing) editorCanvas.restore(page.drawing); updateHistoryButtons(editorCanvas); }
  function setEditorMode(mode) { const area = $('#editor-area'); const isText = mode === 'text'; area.classList.toggle('text-mode', isText); area.classList.toggle('draw-mode', !isText); $('#mode-draw').classList.toggle('active', !isText); $('#mode-text').classList.toggle('active', isText); $('#drawing-canvas').style.pointerEvents = isText ? 'none' : 'auto'; if (isText) $('#text-layer').focus(); }
  function updateHistoryButtons(canvas) { $('#btn-undo').disabled = !canvas.canUndo(); $('#btn-redo').disabled = !canvas.canRedo(); }
  function bindCanvasControls(canvas) { $('#mode-draw').onclick = () => setEditorMode('draw'); $('#mode-text').onclick = () => setEditorMode('text'); document.querySelectorAll('[data-tool]').forEach(button => button.onclick = () => { document.querySelectorAll('[data-tool]').forEach(item => item.classList.remove('active')); button.classList.add('active'); canvas.setTool(button.dataset.tool); }); document.querySelectorAll('.color-preset').forEach(button => button.onclick = () => { document.querySelectorAll('.color-preset').forEach(item => item.classList.remove('active')); button.classList.add('active'); canvas.setColor(button.dataset.color); }); $('#color-picker').oninput = event => canvas.setColor(event.target.value); $('#size-slider').oninput = event => { $('#size-display').textContent = event.target.value; canvas.setSize(event.target.value); }; $('#btn-clear').onclick = () => canvas.clear(); $('#btn-undo').onclick = () => { canvas.undo(); updateHistoryButtons(canvas); }; $('#btn-redo').onclick = () => { canvas.redo(); updateHistoryButtons(canvas); }; }
  function renderDashboard() { const notebooks = InkStorage.data.notebooks; $('#stat-notebooks').textContent = notebooks.length; $('#stat-pages').textContent = notebooks.reduce((total, item) => total + item.pages.length, 0); $('#stat-cal').textContent = Object.keys(InkStorage.data.calendar).reduce((total, key) => total + (InkStorage.data.calendar[key].events || []).length, 0); $('#greeting-sub span').textContent = new Date().toLocaleDateString(undefined, { dateStyle: 'long' }); const recent = $('#recent-notebooks'); recent.innerHTML = ''; notebooks.slice(0, 6).forEach(notebook => { const item = document.createElement('div'); item.className = 'recent-item'; const label = document.createElement('span'); label.textContent = '📓 ' + notebook.name; const button = document.createElement('button'); button.className = 'btn btn-secondary'; button.textContent = 'Open'; button.onclick = () => openNotebook(notebook.id); item.append(label, button); recent.appendChild(item); }); renderUpcomingEvents(); }
  function renderUpcomingEvents() { const list = $('#mini-calendar'); const upcoming = []; const today = new Date(); today.setHours(0, 0, 0, 0); Object.entries(InkStorage.data.calendar).forEach(([key, day]) => { (day.events || []).forEach(event => { const date = new Date(key + 'T12:00:00'); if (date >= today) upcoming.push({ key, date, event }); }); }); upcoming.sort((a, b) => a.date - b.date); list.innerHTML = ''; if (!upcoming.length) { list.innerHTML = '<div class="upcoming-empty">Your upcoming events will appear here.</div>'; return; } upcoming.slice(0, 5).forEach(({ key, date, event }) => { const item = document.createElement('button'); item.className = 'upcoming-item'; item.style.setProperty('--event-color', event.color || '#8b7cf6'); const dateLabel = document.createElement('span'); dateLabel.className = 'upcoming-date'; dateLabel.textContent = date.toLocaleDateString(undefined, { month: 'short', day: 'numeric' }); const title = document.createElement('span'); title.className = 'upcoming-title'; title.textContent = event.title; const time = document.createElement('small'); time.textContent = event.time || 'All day'; item.append(dateLabel, title, time); item.onclick = () => { showView('calendar'); selectDate(key); }; list.appendChild(item); }); }
  function renderCalendar() { InkCalendar.render(selectDate); }
  function selectDate(key) { selectedCalendarDate = key; const panel = $('#calendar-note-panel'); panel.classList.add('open'); $('#cal-note-date').textContent = new Date(key + 'T12:00:00').toLocaleDateString(undefined, { dateStyle: 'long' }); $('#cal-note-text').textContent = InkStorage.data.calendar[key]?.text || ''; $('#cal-note-text').oninput = () => { InkStorage.data.calendar[key] = { ...(InkStorage.data.calendar[key] || {}), text: $('#cal-note-text').innerText }; InkStorage.save(); InkCalendar.render(selectDate); }; renderEvents(key); }
  function renderEvents(key) { const day = InkStorage.data.calendar[key] || {}; const events = day.events || []; const list = $('#calendar-events'); list.innerHTML = ''; if (!events.length) { list.innerHTML = '<div class="events-empty">No events yet</div>'; } events.forEach(event => { const item = document.createElement('div'); item.className = 'calendar-event'; item.style.setProperty('--event-color', event.color || '#8b7cf6'); const details = document.createElement('div'); const title = document.createElement('strong'); title.textContent = event.title; details.appendChild(title); if (event.time) { const time = document.createElement('small'); time.textContent = event.time; details.appendChild(time); } const remove = document.createElement('button'); remove.type = 'button'; remove.className = 'event-delete-btn'; remove.textContent = '×'; remove.title = 'Delete event'; remove.onclick = () => { day.events = events.filter(entry => entry.id !== event.id); InkStorage.data.calendar[key] = day; InkStorage.save(); renderEvents(key); InkCalendar.render(selectDate); }; item.append(details, remove); list.appendChild(item); }); }
  function addEvent() { const title = $('#event-title').value.trim(); if (!selectedCalendarDate) return; if (!title) { toast('Add a title first'); $('#event-title').focus(); return; } const day = InkStorage.data.calendar[selectedCalendarDate] || {}; day.events = [...(day.events || []), { id: 'event-' + Date.now(), title, time: $('#event-time').value, color: $('#event-color').value }]; InkStorage.data.calendar[selectedCalendarDate] = day; InkStorage.save(); $('#event-title').value = ''; $('#event-time').value = ''; renderEvents(selectedCalendarDate); InkCalendar.render(selectDate); toast('Event added'); }
  function exportPng() { if (!editorCanvas || !InkNotebook.currentNotebook) { toast('Open a notebook page first'); return; } const notebook = InkStorage.data.notebooks.find(item => item.id === InkNotebook.currentNotebook); const page = notebook?.pages.find(item => item.id === InkNotebook.currentPage); const link = document.createElement('a'); link.href = editorCanvas.toDataUrl(); link.download = (notebook?.name || 'inkpad') + '-' + (page?.name || 'page') + '.png'; link.click(); toast('Page exported'); }
  function createTemplate(template) { const templates = { blank: { name: 'Blank Notes', text: '' }, journal: { name: 'Daily Journal', text: 'What is on my mind today?\n\nThree things I am grateful for:\n1. \n2. \n3. \n\nToday\'s focus:\n' }, meeting: { name: 'Meeting Notes', text: 'Meeting: \nDate: \nAttendees: \n\nAgenda\n\nNotes\n\nAction items\n- ' }, sketch: { name: 'Brainstorm Canvas', text: 'Idea:\n\nQuestions:\n\nNext steps:\n' } }; const preset = templates[template] || templates.blank; const notebook = InkNotebook.create(preset.name); notebook.pages[0].text = preset.text; InkStorage.save(); refreshSidebar(); openNotebook(notebook.id); toast(preset.name + ' created'); }
  function exportData() { const blob = new Blob([InkStorage.export()], { type: 'application/json' }); const link = document.createElement('a'); link.href = URL.createObjectURL(blob); link.download = 'inkpad-backup.json'; link.click(); URL.revokeObjectURL(link.href); }
  function importData() { const input = document.createElement('input'); input.type = 'file'; input.accept = '.json,application/json'; input.onchange = () => { const file = input.files[0]; if (!file) return; const reader = new FileReader(); reader.onload = () => { try { InkStorage.import(reader.result); location.reload(); } catch (error) { toast('That backup file could not be imported'); } }; reader.readAsText(file); }; input.click(); }
  document.documentElement.dataset.theme = localStorage.getItem('inkpad-theme') || 'dark';
  document.querySelectorAll('.nav-item').forEach(item => item.onclick = () => showView(item.dataset.view));
  document.querySelectorAll('[id^="sidebar-toggle"]').forEach(button => button.onclick = toggleSidebar);
  document.querySelectorAll('[id^="theme-toggle"]').forEach(button => button.onclick = toggleTheme);
  ['home-create-nb', 'add-notebook-btn', 'dash-new-notebook'].forEach(id => $('#' + id).onclick = createNotebook);
  ['add-folder-btn', 'dash-new-folder'].forEach(id => $('#' + id).onclick = createFolder);
  $('#home-open-cal').onclick = () => showView('calendar'); $('#btn-export-png').onclick = exportPng; $('#btn-export-json').onclick = exportData; $('#btn-import-json').onclick = importData; $('#cal-prev').onclick = () => { InkCalendar.previous(); renderCalendar(); }; $('#cal-next').onclick = () => { InkCalendar.next(); renderCalendar(); }; $('#cal-today').onclick = () => { InkCalendar.today(); renderCalendar(); }; $('#cal-close-panel').onclick = () => $('#calendar-note-panel').classList.remove('open'); $('#add-event-btn').onclick = addEvent; $('#event-title').onkeydown = event => { if (event.key === 'Enter') addEvent(); }; document.querySelectorAll('[data-template]').forEach(card => card.onclick = () => createTemplate(card.dataset.template));
  refreshSidebar(); renderDashboard();
  document.addEventListener('inkpad:sidebar-refresh', refreshSidebar);
  document.addEventListener('inkpad:saved', () => { $('#save-indicator').title = 'Auto-saved'; });
});
