window.InkNotebook = (() => {
  let currentNotebook = null; let currentPage = null;
  const openFolders = new Set();
  function notebookItem(notebook, onOpen, onDoubleOpen, nested) { const item = document.createElement('li'); item.className = 'notebook-list-item' + (nested ? ' nested-notebook' : '') + (notebook.id === currentNotebook ? ' active' : ''); item.textContent = '📓 ' + notebook.name; item.draggable = true; item.title = 'Drag into a folder'; item.ondragstart = event => { event.dataTransfer.setData('text/plain', notebook.id); event.dataTransfer.effectAllowed = 'move'; item.classList.add('dragging'); }; item.ondragend = () => item.classList.remove('dragging'); item.onclick = () => onOpen(notebook.id); item.ondblclick = () => onDoubleOpen(notebook.id); return item; }
  function renderSidebar(onOpen, onDoubleOpen, onFolderOpen) { const list = document.querySelector('#notebooks-list'); list.innerHTML = ''; const assigned = new Set(); InkStorage.data.folders.forEach(folder => { const item = document.createElement('li'); const expanded = openFolders.has(folder.id); item.className = 'notebook-list-item folder-list-item' + (expanded ? ' expanded' : ''); item.textContent = (expanded ? '▾ ' : '▸ ') + '📁 ' + folder.name; item.title = 'Click to expand, double-click to open'; item.ondragover = event => { event.preventDefault(); event.dataTransfer.dropEffect = 'move'; item.classList.add('drop-target'); }; item.ondragleave = () => item.classList.remove('drop-target'); item.ondrop = event => { event.preventDefault(); item.classList.remove('drop-target'); moveToFolder(event.dataTransfer.getData('text/plain'), folder.id); }; item.onclick = () => { if (openFolders.has(folder.id)) openFolders.delete(folder.id); else openFolders.add(folder.id); renderSidebar(onOpen, onDoubleOpen, onFolderOpen); }; item.ondblclick = () => onFolderOpen(folder.id); list.appendChild(item); if (expanded) { const children = document.createElement('ul'); children.className = 'folder-contents'; InkStorage.data.notebooks.filter(notebook => notebook.folderId === folder.id).forEach(notebook => { assigned.add(notebook.id); children.appendChild(notebookItem(notebook, onOpen, onDoubleOpen, true)); }); list.appendChild(children); } }); InkStorage.data.notebooks.filter(notebook => !assigned.has(notebook.id) && !notebook.folderId).forEach(notebook => list.appendChild(notebookItem(notebook, onOpen, onDoubleOpen, false))); }
  function open(notebookId, pageId, callbacks) { const notebook = InkStorage.data.notebooks.find(item => item.id === notebookId) || InkStorage.data.notebooks[0]; if (!notebook) return; currentNotebook = notebook.id; currentPage = pageId || notebook.pages[0].id; callbacks.render(notebook, notebook.pages.find(page => page.id === currentPage) || notebook.pages[0]); }
  function create(name) { const notebook = { id: 'nb-' + Date.now(), name: name || 'Untitled Notebook', color: '#8b7cf6', folderId: null, pages: [{ id: 'page-' + Date.now(), name: 'New Page', text: '' }] }; InkStorage.data.notebooks.push(notebook); InkStorage.save(); return notebook; }
  function createFolder(name) { const folder = { id: 'folder-' + Date.now(), name: name || 'Untitled Folder' }; InkStorage.data.folders.push(folder); InkStorage.save(); return folder; }
  function moveToFolder(notebookId, folderId) { const notebook = InkStorage.data.notebooks.find(item => item.id === notebookId); if (!notebook || !InkStorage.data.folders.some(folder => folder.id === folderId)) return; notebook.folderId = folderId; openFolders.add(folderId); InkStorage.save(); document.dispatchEvent(new CustomEvent('inkpad:sidebar-refresh')); }
  function addPage() { const notebook = InkStorage.data.notebooks.find(item => item.id === currentNotebook); if (!notebook) return null; const page = { id: 'page-' + Date.now(), name: 'New Page', text: '' }; notebook.pages.push(page); InkStorage.save(); currentPage = page.id; return page; }
  return { renderSidebar, open, create, createFolder, moveToFolder, addPage, get currentNotebook() { return currentNotebook; }, get currentPage() { return currentPage; } };
})();
